import { useCallback, useEffect, useMemo, useState } from "react";
import { apiClient, type AdminCluster, type AdminKnowledge, type AdminOverview, type AdminTicket } from "../services/apiClient";
import { AdminVoiceDraft } from "../components/AdminVoiceDraft";

type Page = "home" | "tickets" | "stats" | "knowledge";
type StatsData = Awaited<ReturnType<typeof apiClient.adminStats>>;
const statuses = ["open", "claimed", "waiting", "escalated", "resolved"] as const;
const title = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, letter => letter.toUpperCase());
const formatDate = (value: string) => new Date(value).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" });

export function AdminWorkspaceComplete({ onExit }: { onExit: () => void }) {
  const [page, setPage] = useState<Page>("home"); const [overview, setOverview] = useState<AdminOverview | null>(null);
  const [tickets, setTickets] = useState<AdminTicket[]>([]); const [clusters, setClusters] = useState<AdminCluster[]>([]);
  const [knowledge, setKnowledge] = useState<AdminKnowledge[]>([]); const [stats, setStats] = useState<StatsData | null>(null);
  const [selected, setSelected] = useState<AdminTicket | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const refresh = useCallback(async () => { setBusy(true); try { const [o,t,c,k,s] = await Promise.all([apiClient.adminOverview(),apiClient.adminTickets(),apiClient.adminClusters(),apiClient.adminKnowledge(),apiClient.adminStats()]); setOverview(o);setTickets(t);setClusters(c);setKnowledge(k);setStats(s);setError(""); } catch { setError("We couldn’t load coordinator data. Your changes are safe; check the backend and try again."); } finally { setBusy(false); } }, []);
  useEffect(() => { void refresh(); const timer = window.setInterval(() => void refresh(), 30_000); return () => clearInterval(timer); }, [refresh]);
  return <main className="admin-shell"><Sidebar page={page} setPage={setPage} onExit={onExit}/><section className="admin-main">{error&&<Notice text={error}/>} {page==="home"&&<><Home overview={overview} onTickets={()=>setPage("tickets")} onSelect={setSelected}/><RecentUpdates overview={overview}/></>} {page==="tickets"&&<Tickets tickets={tickets} clusters={clusters} refresh={refresh} select={setSelected}/>} {page==="stats"&&<Stats stats={stats}/>} {page==="knowledge"&&<Knowledge documents={knowledge} refresh={refresh}/>}</section>{selected&&<TicketDrawer ticket={selected} clusters={clusters} close={()=>setSelected(null)} saved={async body=>{await apiClient.updateAdminTicket(selected.id,body);setSelected(null);await refresh();}}/>}{busy&&<span className="admin-sync">Refreshing…</span>}</main>;
}

function Sidebar({page,setPage,onExit}:{page:Page;setPage:(p:Page)=>void;onExit:()=>void}) { return <aside className="admin-sidebar"><button className="admin-brand" onClick={()=>setPage("home")}><span>M</span>Margdarshak <small>AI</small></button><p>Coordinator workspace</p><nav>{(["home","tickets","stats","knowledge"] as Page[]).map(item=><button key={item} className={page===item?"active":""} onClick={()=>setPage(item)}>{title(item)}</button>)}</nav><button className="admin-exit" onClick={onExit}>Student experience ↗</button></aside> }
function Header({kicker,name,copy,action}:{kicker:string;name:string;copy:string;action?:React.ReactNode}) { return <header className="admin-header compact"><div><p className="admin-kicker">{kicker}</p><h1>{name}</h1><p>{copy}</p></div>{action}</header> }
function Home({overview,onTickets,onSelect}:{overview:AdminOverview|null;onTickets:()=>void;onSelect:(t:AdminTicket)=>void}) { return <><Header kicker="Placement operations" name="Coordinator workspace" copy="Prioritise urgent questions, keep ownership visible, and turn resolutions into trusted guidance." action={<span className="backend-status">● Backend connected</span>}/><div className="metric-grid">{statuses.map(s=><article className="metric-card" key={s}><span>{title(s)}</span><strong>{overview?.metrics[s]??0}</strong></article>)}</div><SectionHeading kicker="Priority queue" name="Needs attention now" action={<button onClick={onTickets}>View tickets →</button>}/><div className="priority-grid">{overview?.priority_tickets.length?overview.priority_tickets.map(t=><button key={t.id} className="priority-card" onClick={()=>onSelect(t)}><Badge value={t.intelligence.urgency}/><h3>{t.issue_summary}</h3><p>{t.placement.company||"Unassigned"} · {t.student.name}</p></button>):<Empty text="No urgent tickets right now."/>}</div><SectionHeading kicker="Active placement drives" name="Current drives"/><div className="drive-grid">{overview?.active_drives.map(d=><article className="drive-card" key={d.id}><span>ACTIVE</span><h3>{d.company}</h3><p>{d.policy}</p></article>)}</div></> }

function Tickets({tickets,clusters,refresh,select}:{tickets:AdminTicket[];clusters:AdminCluster[];refresh:()=>Promise<void>;select:(t:AdminTicket)=>void}) {
  const empty={drive:"",company:"",round:"",coordinator:"",language:"",urgency:""};
  const [filters,setFilters]=useState(empty); const [clusterName,setClusterName]=useState("");
  const shown=useMemo(()=>tickets.filter(t=>(!filters.drive||t.placement.drive_id===filters.drive)&&(!filters.company||t.placement.company===filters.company)&&(!filters.round||t.placement.round===filters.round)&&(!filters.coordinator||t.intelligence.assigned_coordinator===filters.coordinator)&&(!filters.language||t.intelligence.language===filters.language)&&(!filters.urgency||t.intelligence.urgency===filters.urgency)),[tickets,filters]);
  const values=(pick:(ticket:AdminTicket)=>string|null)=>[...new Set(tickets.map(pick).filter(Boolean))] as string[];
  return <><Header kicker="Ticket triage" name="Tickets" copy="Triage questions, assign ownership, link repeated issues, and close the loop." action={<button className="outline-button" onClick={()=>void refresh()}>↻ Refresh now</button>}/>
    <div className="admin-filters"><Select label="Drive ID" value={filters.drive} options={values(t=>t.placement.drive_id)} change={drive=>setFilters({...filters,drive})}/><Select label="Company" value={filters.company} options={values(t=>t.placement.company)} change={company=>setFilters({...filters,company})}/><Select label="Round" value={filters.round} options={values(t=>t.placement.round)} change={round=>setFilters({...filters,round})}/><Select label="Coordinator" value={filters.coordinator} options={values(t=>t.intelligence.assigned_coordinator)} change={coordinator=>setFilters({...filters,coordinator})}/><Select label="Language" value={filters.language} options={values(t=>t.intelligence.language)} change={language=>setFilters({...filters,language})}/><Select label="Urgency" value={filters.urgency} options={["low","medium","high","critical"]} change={urgency=>setFilters({...filters,urgency})}/><button onClick={()=>setFilters(empty)}>Clear filters</button></div>
    <div className="kanban">{statuses.map(status=><section key={status}><header><strong>{title(status)}</strong><span>{shown.filter(t=>t.status===status).length}</span></header>{shown.filter(t=>t.status===status).map(t=><button key={t.id} className="ticket-card" onClick={()=>select(t)}><div><Badge value={t.intelligence.urgency}/><span>{Math.round(t.confidence_score*100)}% confidence</span></div><h3>{t.issue_summary}</h3><p>{t.placement.company||"Unassigned drive"}</p><dl><dt>Student</dt><dd>{t.student.enrollment_number}</dd><dt>Language</dt><dd>{t.intelligence.language}</dd><dt>Owner</dt><dd>{t.intelligence.assigned_coordinator||"Unclaimed"}</dd></dl><time>{formatDate(t.created_at)}</time></button>)}</section>)}</div>
    <SectionHeading kicker="Repeated issue detection" name="Issue clusters"/><form className="cluster-create" onSubmit={async e=>{e.preventDefault();if(!clusterName.trim())return;await apiClient.createAdminCluster({title:clusterName,urgency:"medium"});setClusterName("");await refresh();}}><input value={clusterName} onChange={e=>setClusterName(e.target.value)} placeholder="New cluster name"/><button>Create cluster</button></form><div className="cluster-grid">{clusters.map(c=><Cluster key={c.id} cluster={c} refresh={refresh}/>)}</div></>;
}
function Cluster({cluster,refresh}:{cluster:AdminCluster;refresh:()=>Promise<void>}) { const [message,setMessage]=useState(cluster.incident_update||cluster.response_draft||""); const [draft,setDraft]=useState(false); return <article className="cluster-card"><div><Badge value={cluster.urgency}/><span>{cluster.affected_students} affected · score {cluster.priority_score}</span></div><h3>{cluster.title}</h3><p>{cluster.company_name||"All drives"} · {title(cluster.status)}</p><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Coordinator notes or approved update"/><AdminVoiceDraft onTranscript={value=>setMessage(previous=>`${previous} ${value}`.trim())}/><div className="cluster-actions"><button onClick={async()=>{setDraft(true);const r=await apiClient.draftCluster(cluster.id,message||"The placement team is reviewing this issue.");setMessage(r.draft);setDraft(false);}}>{draft?"Drafting…":"Generate professional draft"}</button><button disabled={!message.trim()} onClick={async()=>{await apiClient.publishCluster(cluster.id,message);await refresh();}}>Approve & send</button><button className="resolve" onClick={async()=>{await apiClient.resolveCluster(cluster.id);await refresh();}}>Resolve cluster</button></div></article> }

function TicketDrawer({ticket,clusters,close,saved}:{ticket:AdminTicket;clusters:AdminCluster[];close:()=>void;saved:(b:Parameters<typeof apiClient.updateAdminTicket>[1])=>Promise<void>}) {
  const [form,setForm]=useState({status:ticket.status,assigned_coordinator:ticket.intelligence.assigned_coordinator||"",urgency:ticket.intelligence.urgency,language:ticket.intelligence.language,category:ticket.intelligence.category,cluster_id:ticket.intelligence.cluster_id||"",original_request:ticket.original_request||"",conversation_summary:ticket.conversation_summary||""});
  return <div className="ticket-drawer-backdrop" onMouseDown={close}><aside className="ticket-drawer" onMouseDown={e=>e.stopPropagation()}><button className="drawer-close" onClick={close}>×</button><p className="admin-kicker">Ticket {ticket.student.enrollment_number}</p><h2>{ticket.issue_summary}</h2>
    <Detail name="Student" rows={[["Name",ticket.student.name],["Enrollment",ticket.student.enrollment_number],["Email",ticket.student.email]]}/>
    <Detail name="Issue" rows={[["Original request",ticket.original_request||"Not recorded"],["Conversation summary",ticket.conversation_summary||"Not recorded"],["Category",ticket.intelligence.category]]}/>
    <Detail name="Placement context" rows={[["Company",ticket.placement.company||"Not identified"],["Drive",ticket.placement.drive_id||"Not linked"],["Role",ticket.placement.role||"Not recorded"],["Round",ticket.placement.round||"Not recorded"],["Deadline",ticket.placement.deadline||"Not recorded"]]}/>
    <Detail name="AI intelligence" rows={[["Language",ticket.intelligence.language],["Confidence",`${Math.round(ticket.confidence_score*100)}%`],["Urgency",ticket.intelligence.urgency],["Source",ticket.source||"No verified source matched"]]}/>
    <div className="drawer-form"><Select label="Status" value={form.status} options={[...statuses]} change={status=>setForm({...form,status:status as AdminTicket["status"]})}/><Select label="Urgency" value={form.urgency} options={["low","medium","high","critical"]} change={urgency=>setForm({...form,urgency:urgency as AdminTicket["intelligence"]["urgency"]})}/><label>Coordinator<input value={form.assigned_coordinator} onChange={e=>setForm({...form,assigned_coordinator:e.target.value})}/></label><label>Language<input value={form.language} onChange={e=>setForm({...form,language:e.target.value})}/></label><label>Category<input value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><Select label="Issue cluster" value={form.cluster_id} options={clusters.map(c=>c.id)} optionLabel={id=>clusters.find(c=>c.id===id)?.title||id} change={cluster_id=>setForm({...form,cluster_id})}/><label className="full-field">Original request<textarea value={form.original_request} onChange={e=>setForm({...form,original_request:e.target.value})}/></label><label className="full-field">Conversation summary<textarea value={form.conversation_summary} onChange={e=>setForm({...form,conversation_summary:e.target.value})}/></label></div>
    <div className="drawer-actions"><button onClick={()=>void saved({...form,cluster_id:form.cluster_id||null})}>Save ticket</button><button className="resolve" onClick={()=>void saved({...form,status:"resolved",conversation_summary:`Dismissed by coordinator. ${form.conversation_summary}`.trim(),cluster_id:form.cluster_id||null})}>Dismiss</button><button className="outline-button" onClick={close}>Cancel</button></div></aside></div>;
}

function RecentUpdates({overview}:{overview:AdminOverview|null}) { return <><SectionHeading kicker="Operational activity" name="Recent updates"/><div className="recent-updates">{overview?.recent_updates.map((item,index)=><article key={`${item.at}-${index}`}><span>{title(item.kind)}</span><p>{item.text}</p><time>{formatDate(item.at)}</time></article>)}{!overview?.recent_updates.length&&<Empty text="No recent activity."/>}</div></> }
function Stats({stats}:{stats:StatsData|null}) { const cards=[["Total conversations",stats?.total_conversations],["Tickets created",stats?.tickets_created],["Tickets resolved",stats?.tickets_resolved],["Students assisted",stats?.students_assisted],["Average resolution (hours)",stats?.average_resolution_time_hours],["Active clusters",stats?.active_clusters]]; return <><Header kicker="Operational patterns" name="Stats" copy="Focused signals for staffing and issue prevention."/><div className="metric-grid">{cards.map(([k,v])=><article className="metric-card" key={String(k)}><span>{k}</span><strong>{v??0}</strong></article>)}</div><div className="analytics-grid"><Bars name="Issue categories" values={stats?.most_common_issue_categories}/><Bars name="Requested companies" values={stats?.most_requested_companies}/><Bars name="Languages" values={stats?.most_common_languages}/></div></> }
function Bars({name,values={}}:{name:string;values?:Record<string,number>}) { const max=Math.max(1,...Object.values(values)); return <section className="chart-card"><h2>{name}</h2>{Object.entries(values).map(([k,v])=><div className="bar-row" key={k}><span>{k}</span><i style={{width:`${v/max*100}%`}}/><b>{v}</b></div>)}{!Object.keys(values).length&&<Empty text="No data yet."/>}</section> }

function Knowledge({documents,refresh}:{documents:AdminKnowledge[];refresh:()=>Promise<void>}) { const blank={title:"",company_name:"",version_label:"",source_reference:"manual://coordinator-entry",eligibility:"",ctc:"",deadline:"",application_url:"",instructions:""}; const [form,setForm]=useState(blank); const set=(key:string,value:string)=>setForm({...form,[key]:value}); return <><Header kicker="Approved institutional guidance" name="Knowledge approval" copy="Review policy versions and imports before they become student-facing guidance."/><div className="knowledge-layout"><div><form className="knowledge-form" onSubmit={async e=>{e.preventDefault();await apiClient.createKnowledge({title:form.title,company_name:form.company_name,document_type:"placement_policy",version_label:form.version_label,source_reference:form.source_reference,content:{eligibility:form.eligibility,ctc:form.ctc,deadline:form.deadline,application_url:form.application_url,instructions:form.instructions}});setForm(blank);await refresh();}}><h2>Create policy draft</h2>{Object.entries(form).map(([key,value])=><label key={key}>{title(key)}<input required={!(["company_name","ctc","application_url"].includes(key))} type={key==="deadline"?"date":"text"} value={value} onChange={e=>set(key,e.target.value)}/></label>)}<button className="primary-admin">Save as draft</button></form><ShortlistImport refresh={refresh}/></div><section className="knowledge-list"><SectionHeading kicker="Knowledge library" name="Available sources"/>{documents.map(d=><article className="knowledge-row" key={d.id}><div><span className={`doc-status ${d.status}`}>{d.status}</span><h3>{d.title}</h3><p>{title(d.type)} · {d.company||"University"} · v{d.version}</p><small>{d.source}</small></div><div>{d.status==="draft"&&<button onClick={async()=>{await apiClient.updateKnowledge(d.id,"published");await refresh();}}>Publish</button>}{d.status==="published"&&<button onClick={async()=>{await apiClient.updateKnowledge(d.id,"expired");await refresh();}}>Expire</button>}</div></article>)}</section></div></> }
function ShortlistImport({refresh}:{refresh:()=>Promise<void>}) { const [file,setFile]=useState<File|null>(null); const [preview,setPreview]=useState<Awaited<ReturnType<typeof apiClient.previewShortlist>>|null>(null); const [error,setError]=useState(""); return <section className="shortlist-import"><h2>Import shortlist</h2><p>Upload CSV/XLSX, validate required columns, review records, then confirm.</p><input type="file" accept=".csv,.xlsx" onChange={async e=>{const value=e.target.files?.[0]||null;setFile(value);setPreview(null);if(value)try{setPreview(await apiClient.previewShortlist(value));setError("");}catch{setError("Invalid file or missing required columns.");}}}/>{error&&<Notice text={error}/>} {preview&&<><strong>{preview.record_count} validated records</strong><div className="import-preview">{preview.preview.slice(0,5).map((row,i)=><p key={i}>{row.name} · {row.company} · {row.round}</p>)}</div><button onClick={async()=>{if(!file)return;await apiClient.importShortlist({title:file.name,source_reference:`upload://${file.name}`,version_label:new Date().toISOString().slice(0,7),rows:preview.rows});setPreview(null);setFile(null);await refresh();}}>Confirm import</button></>}</section> }

function Select({label,value,options,change,optionLabel=(v)=>title(v)}:{label:string;value:string;options:readonly string[];change:(v:string)=>void;optionLabel?:(v:string)=>string}) { return <label>{label}<select value={value} onChange={e=>change(e.target.value)}><option value="">All / none</option>{options.map(o=><option value={o} key={o}>{optionLabel(o)}</option>)}</select></label> }
function SectionHeading({kicker,name,action}:{kicker:string;name:string;action?:React.ReactNode}) { return <div className="section-heading admin-section"><div><p className="admin-kicker">{kicker}</p><h2>{name}</h2></div>{action}</div> }
function Detail({name,rows}:{name:string;rows:string[][]}) { return <section className="detail-block"><h3>{name}</h3><dl>{rows.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></section> }
function Badge({value}:{value:string}) { return <span className={`urgency ${value}`}>{value}</span> }
function Empty({text}:{text:string}) { return <p className="admin-empty">{text}</p> }
function Notice({text}:{text:string}) { return <div className="admin-error">{text}</div> }
